FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY .npmrc ./

COPY apps/admin-panel-web/package.json ./apps/admin-panel-web/

RUN npm install

COPY . .

WORKDIR /app/apps/admin-panel-web

EXPOSE 3000

CMD ["npm","run","dev"]